services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampleBank
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - spring-cloud-network
  bank-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: com.example/examplebank
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge