spring:
  application:
    name: spring-boot-example-bank-service
  datasource:
    url: jdbc:mysql://localhost:3306/exampleBank?useSSL=false&serverTimezone=UTC
    username: dev
    password: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  profiles:
    active: prod
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always
      continue-on-error: true
logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: debug
