spring:
  application:
    name: spring-boot-example-bank-service
  datasource:
    url: jdbc:mysql://mysqldb:3306/exampleBank?allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dev
    password: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: debug
